language: go
sudo: required

os:
  - linux
  - osx
go: 1.12.x

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - gnome-keyring
      - libsecret-1-dev
      - python-gnomekeyring

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      dbus-launch /usr/bin/python -c \
        "import gnomekeyring;gnomekeyring.create_sync('login', '');"
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      chmod +x ./script/cibuild
      xvfb-run ./script/cibuild
      bash <(curl -s https://codecov.io/bash)
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      env GO111MODULE=on go test ./...
    fi
