version: "{build}"

image: Visual Studio 2017
platform:
  - x64

branches:
  only:
    - /master|^v\d+\.\d+\.\d+$/

clone_depth: 10

install:
  - go get golang.org/dl/go1.12.9
  - go1.12.9 download


build_script:
  - go1.12.9 test ./...

test: off
deploy: off
