version: "{build}"

image: Visual Studio 2017
platform:
  - x64

branches:
  only:
    - /master|^v\d+\.\d+\.\d+$/

clone_depth: 10


build_script:
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - choco install -y make
  - make test

after_build:
  - bash <(curl -s https://codecov.io/bash)

test: off
deploy: off
