version: "{build}"

image: Visual Studio 2017
platform:
  - x64

branches:
  only:
    - /master|^v\d+\.\d+\.\d+$/

clone_depth: 10


build_script:
  - set PATH=c:\MinGW\bin;%PATH%
  - go test ./...

test: off
deploy: off
