version: '{build}'

image: Visual Studio 2017
platform:
  - x64

branches:
  only:
    - /master|^v\d+\.\d+\.\d+$/

clone_depth: 10

before_test:
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - choco install -y make codecov

test_script:
  - make test

after_test:
  - codecov

build: off
deploy: off
