version: 2

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run:
          name: go lint
          command: make lint
      - run:
          name: go test
          command: make test
      - run:
          name: go build
          command: make build
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)

  release:
    docker:
      - image: rdaniels6813/semantic-release-alpine:latest
    steps:
      - checkout
      - run:
          name: Release
          command: make release

workflows:
  version: 2
  build:
    jobs:
      - 'builds'
      - release:
          requires:
            - 'build'
          filters:
            branches:
              only: master
